Repository hmcts/et-pet-et3, pull requests merged in 2024-09, with the labels that each got.

#654 RST-6254 - Allow EtDateType to handle 0/0/0 date and return valid error
  Gemfile.lock
  app/forms/claimants_detail.rb
  app/types/et_date_type.rb
  app/validators/date_validator.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et3-pr-654

#673 Rst 6837 - Updated confirmation page for use with new API
  .ruby-lsp/Gemfile.lock
  .vscode/settings.json
  app/controllers/form_submissions_controller.rb
  app/views/form_submissions/index.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  spec/features/access_form_submission_page_spec.rb
  spec/support/capybara_selectors/summary_list_row_labelled.rb
  spec/support/messaging/en.yml
  spec/support/page_objects/form_submission_page.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et3-pr-673

#676 Revert "RST-6254 - Allow EtDateType to handle 0/0/0 date and return valid error"
  app/forms/claimants_detail.rb
  app/types/et_date_type.rb
  app/validators/date_validator.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et3-pr-676

#677 (RST-6878) Added specs for EtDateType to fix pipeline
  .ruby-lsp/Gemfile.lock
  spec/types/et_date_type_spec.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et3-pr-677

#678 (RST-6878) Improved coverage of et date type
  app/types/et_date_type.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et3-pr-678

#675 (RST-6875) Welsh content for submission page
  app/views/form_submissions/index.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  spec/support/capybara/capybara_driver_helper.rb
  spec/support/messaging/cy.yml
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et3-pr-675
